# Generated by Django 5.2.10 on 2026-01-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ratinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinghistory',
            name='game_mode',
            field=models.CharField(choices=[('pvp', 'Player vs Player'), ('pve', 'Player vs AI')], default='pvp', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='blitz_pve_games_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='bullet_pve_games_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='elo_blitz_pve',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='user',
            name='elo_bullet_pve',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='user',
            name='elo_rapid_pve',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='user',
            name='pve_games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pve_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pve_games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rapid_pve_games_count',
            field=models.IntegerField(default=0),
        ),
    ]
