# Generated by Django 5.2.10 on 2026-01-26 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('pvp', 'Player vs Player'), ('pve', 'Player vs AI')], max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Player'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'Easy - Demogorgon'), (2, 'Medium - Alpha AI'), (3, 'Hard - Shadow Monster'), (4, 'Nightmare - Mind Flayer')], null=True)),
                ('board_size', models.IntegerField(default=5)),
                ('ai_won', models.BooleanField(default=False)),
                ('game_state', models.JSONField(default=dict)),
                ('move_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_turn_games', to=settings.AUTH_USER_MODEL)),
                ('player_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_one', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_two', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai_move', models.BooleanField(default=False)),
                ('move_number', models.IntegerField()),
                ('from_position', models.JSONField()),
                ('to_position', models.JSONField()),
                ('captured_position', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.gamesession')),
            ],
            options={
                'verbose_name': 'Game Move',
                'verbose_name_plural': 'Game Moves',
                'ordering': ['move_number'],
                'unique_together': {('game', 'move_number')},
            },
        ),
    ]
