# Generated by Django 5.2.10 on 2026-01-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_add_time_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='pvp_type',
            field=models.CharField(blank=True, choices=[('online', 'Online Ranked'), ('local', 'Local Unranked')], help_text='For PvP games: online (ranked) or local (unranked)', max_length=10, null=True),
        ),
    ]
