# Generated by Django 5.2.10 on 2026-01-27 14:53

from django.db import migrations, models


def convert_online_to_online_ranked(apps, schema_editor):
    """Convert existing 'online' pvp_type to 'online_ranked'."""
    GameSession = apps.get_model('game', 'GameSession')
    GameSession.objects.filter(pvp_type='online').update(pvp_type='online_ranked')


def reverse_online_ranked_to_online(apps, schema_editor):
    """Reverse: convert 'online_ranked' back to 'online'."""
    GameSession = apps.get_model('game', 'GameSession')
    GameSession.objects.filter(pvp_type='online_ranked').update(pvp_type='online')


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_pvp_type'),
    ]

    operations = [
        # First convert data
        migrations.RunPython(convert_online_to_online_ranked, reverse_online_ranked_to_online),
        # Then alter field
        migrations.AlterField(
            model_name='gamesession',
            name='pvp_type',
            field=models.CharField(blank=True, choices=[('local', 'Local (Unranked)'), ('online_ranked', 'Online Ranked'), ('online_unranked', 'Online Unranked')], help_text='For PvP games: local, online_ranked, or online_unranked', max_length=20, null=True),
        ),
    ]
